# Generated by Django 2.1.7 on 2019-12-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_auto_20191213_1202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follows', 'follower')},
        ),
    ]
